modLoader="javafml"
loaderVersioln="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="trom"
version="1.0.0"
displayName="The Rise Of Minerals"
authors="shuixingshow, Jin13583"
description='''This mod add some minerals,weapons,armors and bosses'''

[[dependencies.trom]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.trom]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
